/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author nacho
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
                 setLocationRelativeTo(null);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevo_frame = new javax.swing.JFrame();
        qant_box = new javax.swing.JComboBox<>();
        lbl1_f2 = new javax.swing.JLabel();
        lbl2_f2 = new javax.swing.JLabel();
        tipot_box = new javax.swing.JComboBox<>();
        salir_btn_f2 = new javax.swing.JButton();
        volver_btn_f2 = new javax.swing.JButton();
        titulo_lbl = new javax.swing.JLabel();
        salir_btn = new javax.swing.JButton();
        nuevo_btn = new javax.swing.JButton();

        nuevo_frame.setLocationByPlatform(true);
        nuevo_frame.setMaximumSize(new java.awt.Dimension(300, 300));
        nuevo_frame.setMinimumSize(new java.awt.Dimension(300, 300));

        qant_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "8", "16" }));
        qant_box.setMaximumSize(new java.awt.Dimension(300, 300));
        qant_box.setMinimumSize(new java.awt.Dimension(300, 300));
        qant_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qant_boxActionPerformed(evt);
            }
        });

        lbl1_f2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1_f2.setText("Organizar por:");

        lbl2_f2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2_f2.setText("Cantidad de equipos:");

        tipot_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipos", "Individual" }));
        tipot_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipot_boxActionPerformed(evt);
            }
        });

        salir_btn_f2.setText("Salir");
        salir_btn_f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btn_f2ActionPerformed(evt);
            }
        });

        volver_btn_f2.setText("Volver");
        volver_btn_f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_btn_f2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevo_frameLayout = new javax.swing.GroupLayout(nuevo_frame.getContentPane());
        nuevo_frame.getContentPane().setLayout(nuevo_frameLayout);
        nuevo_frameLayout.setHorizontalGroup(
            nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevo_frameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevo_frameLayout.createSequentialGroup()
                        .addComponent(tipot_box, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevo_frameLayout.createSequentialGroup()
                        .addGroup(nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl2_f2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(lbl1_f2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(nuevo_frameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(volver_btn_f2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salir_btn_f2)))
                        .addGap(19, 19, 19))))
            .addGroup(nuevo_frameLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(qant_box, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        nuevo_frameLayout.setVerticalGroup(
            nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevo_frameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl1_f2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipot_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl2_f2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qant_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver_btn_f2)
                    .addComponent(salir_btn_f2))
                .addContainerGap())
        );

        qant_box.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organizador de Torneos");
        setBackground(new java.awt.Color(88, 7, 14));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        titulo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_lbl.setText("Organizador de Torneos");
        titulo_lbl.setToolTipText("");

        salir_btn.setText("Salir");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });

        nuevo_btn.setText("Nuevo");
        nuevo_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(nuevo_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir_btn)
                .addGap(96, 96, 96))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed

        this.dispose();
        
    }//GEN-LAST:event_salir_btnActionPerformed

    private void qant_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qant_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qant_boxActionPerformed

    private void tipot_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipot_boxActionPerformed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_tipot_boxActionPerformed

    private void nuevo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_btnActionPerformed

        this.dispose();
        nuevo_frame.setVisible(true);
        nuevo_frame.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo_btnActionPerformed

    private void volver_btn_f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_btn_f2ActionPerformed

        nuevo_frame.dispose();
        this.setVisible(true);
                
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_volver_btn_f2ActionPerformed

    private void salir_btn_f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btn_f2ActionPerformed

        nuevo_frame.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_salir_btn_f2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl1_f2;
    private javax.swing.JLabel lbl2_f2;
    private javax.swing.JButton nuevo_btn;
    private javax.swing.JFrame nuevo_frame;
    private javax.swing.JComboBox<String> qant_box;
    private javax.swing.JButton salir_btn;
    private javax.swing.JButton salir_btn_f2;
    private javax.swing.JComboBox<String> tipot_box;
    private javax.swing.JLabel titulo_lbl;
    private javax.swing.JButton volver_btn_f2;
    // End of variables declaration//GEN-END:variables
}
