/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.Random;
import java.util.Scanner;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JTextField;

/**
 *
 * @author nacho
 */
public class Torneo16 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Torneo16() {
        initComponents();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevo_frame = new javax.swing.JFrame();
        qant_box = new javax.swing.JComboBox<>();
        lbl1_f2 = new javax.swing.JLabel();
        lbl2_f2 = new javax.swing.JLabel();
        salir_btn_f2 = new javax.swing.JButton();
        volver_btn_f2 = new javax.swing.JButton();
        lbl3_f2 = new javax.swing.JLabel();
        nombre_txt = new javax.swing.JTextField();
        comenzar_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        indiv_rbttn = new javax.swing.JRadioButton();
        grups_rbttn = new javax.swing.JRadioButton();
        lbl4_f3 = new javax.swing.JLabel();
        deporte_txt = new javax.swing.JTextField();
        filtro = new javax.swing.ButtonGroup();
        torneo16_frame = new javax.swing.JFrame();
        e1_t16 = new javax.swing.JTextField();
        e2_t16 = new javax.swing.JTextField();
        e3_t16 = new javax.swing.JTextField();
        e4_t16 = new javax.swing.JTextField();
        e5_t16 = new javax.swing.JTextField();
        e6_t16 = new javax.swing.JTextField();
        e7_t16 = new javax.swing.JTextField();
        e8_t16 = new javax.swing.JTextField();
        octavo_a = new javax.swing.JTextField();
        octavo_b = new javax.swing.JTextField();
        octavo_c = new javax.swing.JTextField();
        octavo_d = new javax.swing.JTextField();
        semi_a_t16 = new javax.swing.JTextField();
        final1_t16 = new javax.swing.JTextField();
        final2_t16 = new javax.swing.JTextField();
        final_lbl_t16 = new javax.swing.JLabel();
        tyc_2_t16 = new javax.swing.JTextField();
        tyc_1_t16 = new javax.swing.JTextField();
        tyc_lbl_t16 = new javax.swing.JLabel();
        semi_b_t16 = new javax.swing.JTextField();
        b8c_t16 = new javax.swing.JButton();
        b8a_t16 = new javax.swing.JButton();
        re1_t16 = new javax.swing.JTextField();
        re3_t16 = new javax.swing.JTextField();
        re4_t16 = new javax.swing.JTextField();
        re2_t16 = new javax.swing.JTextField();
        re5_t16 = new javax.swing.JTextField();
        re6_t16 = new javax.swing.JTextField();
        b8b_t16 = new javax.swing.JButton();
        re7_t16 = new javax.swing.JTextField();
        re8_t16 = new javax.swing.JTextField();
        b8d_t16 = new javax.swing.JButton();
        r_8a_16 = new javax.swing.JTextField();
        r_8b_16 = new javax.swing.JTextField();
        r_8d_16 = new javax.swing.JTextField();
        r_8c_16 = new javax.swing.JTextField();
        b_4b_16 = new javax.swing.JButton();
        b_4a_16 = new javax.swing.JButton();
        bsemi_a_t16 = new javax.swing.JButton();
        r_semib_t16 = new javax.swing.JTextField();
        r_semia_t16 = new javax.swing.JTextField();
        r_tyc_2_t16 = new javax.swing.JTextField();
        r_final2_t16 = new javax.swing.JTextField();
        b_tyc_t16 = new javax.swing.JButton();
        e9_t16 = new javax.swing.JTextField();
        e10_t16 = new javax.swing.JTextField();
        e11_t16 = new javax.swing.JTextField();
        e12_t16 = new javax.swing.JTextField();
        e13_t16 = new javax.swing.JTextField();
        e14_t16 = new javax.swing.JTextField();
        e15_t16 = new javax.swing.JTextField();
        e16_t16 = new javax.swing.JTextField();
        octavo_e = new javax.swing.JTextField();
        octavo_f = new javax.swing.JTextField();
        octavo_g = new javax.swing.JTextField();
        octavo_h = new javax.swing.JTextField();
        semi_c_t16 = new javax.swing.JTextField();
        semi_d_t16 = new javax.swing.JTextField();
        b8g_t16 = new javax.swing.JButton();
        b8e_t16 = new javax.swing.JButton();
        re9_t16 = new javax.swing.JTextField();
        re11_t16 = new javax.swing.JTextField();
        re12_t16 = new javax.swing.JTextField();
        re10_t16 = new javax.swing.JTextField();
        re13_t16 = new javax.swing.JTextField();
        re14_t16 = new javax.swing.JTextField();
        b8f_t16 = new javax.swing.JButton();
        re15_t16 = new javax.swing.JTextField();
        re16_t16 = new javax.swing.JTextField();
        b8h_t16 = new javax.swing.JButton();
        r_8e_16 = new javax.swing.JTextField();
        r_semic_t16 = new javax.swing.JTextField();
        r_8h_16 = new javax.swing.JTextField();
        b_4c_16 = new javax.swing.JButton();
        b_final_t16 = new javax.swing.JButton();
        r_8g_16 = new javax.swing.JTextField();
        r_8f_16 = new javax.swing.JTextField();
        r_semid_t16 = new javax.swing.JTextField();
        torneo_lbl1 = new javax.swing.JLabel();
        bsemi_b_t16 = new javax.swing.JButton();
        b_4d_16 = new javax.swing.JButton();
        r_final1_t17 = new javax.swing.JTextField();
        r_tyc_1_t16 = new javax.swing.JTextField();
        volver_t16 = new javax.swing.JButton();
        salir_t16 = new javax.swing.JButton();
        tercerpuesto16 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        n1_16 = new javax.swing.JTextField();
        n2_16 = new javax.swing.JTextField();
        n3_16 = new javax.swing.JTextField();
        n4_16 = new javax.swing.JTextField();
        n5_16 = new javax.swing.JTextField();
        n6_16 = new javax.swing.JTextField();
        n7_16 = new javax.swing.JTextField();
        n8_16 = new javax.swing.JTextField();
        aceptar_n16 = new javax.swing.JButton();
        lbl_nombres16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        volver_n16 = new javax.swing.JButton();
        salir_n16 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        n9_16 = new javax.swing.JTextField();
        n10_16 = new javax.swing.JTextField();
        n11_16 = new javax.swing.JTextField();
        n12_16 = new javax.swing.JTextField();
        n13_16 = new javax.swing.JTextField();
        n14_16 = new javax.swing.JTextField();
        n15_16 = new javax.swing.JTextField();
        n16_16 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Ganador16 = new javax.swing.JDialog();
        nombreganador = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        titulo_lbl = new javax.swing.JLabel();
        salir_btn = new javax.swing.JButton();
        nuevo_btn = new javax.swing.JButton();

        nuevo_frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        nuevo_frame.setLocationByPlatform(true);
        nuevo_frame.setMaximumSize(new java.awt.Dimension(292, 400));
        nuevo_frame.setMinimumSize(new java.awt.Dimension(292, 400));
        nuevo_frame.setPreferredSize(new java.awt.Dimension(292, 376));

        qant_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "8", "16" }));
        qant_box.setMaximumSize(new java.awt.Dimension(300, 300));
        qant_box.setMinimumSize(new java.awt.Dimension(300, 300));
        qant_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qant_boxActionPerformed(evt);
            }
        });

        lbl1_f2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1_f2.setText("Organizar por:");
        lbl1_f2.setToolTipText("");

        lbl2_f2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2_f2.setText("Cantidad:");

        salir_btn_f2.setText("Salir");
        salir_btn_f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btn_f2ActionPerformed(evt);
            }
        });

        volver_btn_f2.setText("Volver");
        volver_btn_f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_btn_f2ActionPerformed(evt);
            }
        });

        lbl3_f2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3_f2.setText("Nombre del torneo: ");
        lbl3_f2.setToolTipText("");
        lbl3_f2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl3_f2.setVerifyInputWhenFocusTarget(false);

        nombre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_txtActionPerformed(evt);
            }
        });

        comenzar_btn.setText("Comenzar");
        comenzar_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        comenzar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzar_btnActionPerformed(evt);
            }
        });

        filtro.add(indiv_rbttn);
        indiv_rbttn.setText("Individuales");
        indiv_rbttn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        indiv_rbttn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        indiv_rbttn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                indiv_rbttnFocusGained(evt);
            }
        });
        indiv_rbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiv_rbttnActionPerformed(evt);
            }
        });

        filtro.add(grups_rbttn);
        grups_rbttn.setText("Equipos");
        grups_rbttn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grups_rbttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grups_rbttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indiv_rbttn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grups_rbttn, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indiv_rbttn)
                    .addComponent(grups_rbttn))
                .addContainerGap())
        );

        lbl4_f3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4_f3.setText("Deporte / Actividad:");
        lbl4_f3.setToolTipText("");
        lbl4_f3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl4_f3.setVerifyInputWhenFocusTarget(false);

        deporte_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deporte_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevo_frameLayout = new javax.swing.GroupLayout(nuevo_frame.getContentPane());
        nuevo_frame.getContentPane().setLayout(nuevo_frameLayout);
        nuevo_frameLayout.setHorizontalGroup(
            nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevo_frameLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(qant_box, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(nuevo_frameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl2_f2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(nuevo_frameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(volver_btn_f2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salir_btn_f2)))
                .addGap(19, 19, 19))
            .addComponent(lbl1_f2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl3_f2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nuevo_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl4_f3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(nuevo_frameLayout.createSequentialGroup()
                .addGroup(nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevo_frameLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nuevo_frameLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(comenzar_btn))
                    .addGroup(nuevo_frameLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(deporte_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nuevo_frameLayout.setVerticalGroup(
            nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevo_frameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl1_f2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl2_f2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qant_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl3_f2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl4_f3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deporte_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comenzar_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevo_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver_btn_f2)
                    .addComponent(salir_btn_f2))
                .addContainerGap())
        );

        qant_box.getAccessibleContext().setAccessibleName("");

        torneo16_frame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        torneo16_frame.setLocationByPlatform(true);
        torneo16_frame.setMinimumSize(new java.awt.Dimension(1450, 350));
        torneo16_frame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e1_t16.setEditable(false);
        e1_t16.setBackground(new java.awt.Color(242, 240, 240));
        e1_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e1_t16.setText("Equipo n° 1");
        e1_t16.setMaximumSize(new java.awt.Dimension(86, 28));
        e1_t16.setMinimumSize(new java.awt.Dimension(86, 28));
        e1_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e1_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 86, 28));

        e2_t16.setEditable(false);
        e2_t16.setBackground(new java.awt.Color(242, 240, 240));
        e2_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e2_t16.setText("Equipo n° 2");
        e2_t16.setMaximumSize(new java.awt.Dimension(86, 28));
        e2_t16.setMinimumSize(new java.awt.Dimension(86, 28));
        e2_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e2_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 86, 28));

        e3_t16.setEditable(false);
        e3_t16.setBackground(new java.awt.Color(242, 240, 240));
        e3_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e3_t16.setText("Equipo n° 3");
        e3_t16.setMaximumSize(new java.awt.Dimension(86, 28));
        e3_t16.setMinimumSize(new java.awt.Dimension(86, 28));
        e3_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e3_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 86, 28));

        e4_t16.setEditable(false);
        e4_t16.setBackground(new java.awt.Color(242, 240, 240));
        e4_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e4_t16.setText("Equipo n° 4");
        e4_t16.setMaximumSize(new java.awt.Dimension(86, 28));
        e4_t16.setMinimumSize(new java.awt.Dimension(86, 28));
        e4_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e4_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 86, 28));

        e5_t16.setEditable(false);
        e5_t16.setBackground(new java.awt.Color(242, 240, 240));
        e5_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e5_t16.setText("Equipo n° 5");
        e5_t16.setMaximumSize(new java.awt.Dimension(86, 28));
        e5_t16.setMinimumSize(new java.awt.Dimension(86, 28));
        e5_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e5_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e5_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 86, 28));

        e6_t16.setEditable(false);
        e6_t16.setBackground(new java.awt.Color(242, 240, 240));
        e6_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e6_t16.setText("Equipo n° 6");
        e6_t16.setMaximumSize(new java.awt.Dimension(86, 28));
        e6_t16.setMinimumSize(new java.awt.Dimension(86, 28));
        e6_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e6_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e6_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 86, 28));

        e7_t16.setEditable(false);
        e7_t16.setBackground(new java.awt.Color(242, 240, 240));
        e7_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e7_t16.setText("Equipo n° 7");
        e7_t16.setMaximumSize(new java.awt.Dimension(86, 28));
        e7_t16.setMinimumSize(new java.awt.Dimension(86, 28));
        e7_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e7_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e7_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 86, 28));

        e8_t16.setEditable(false);
        e8_t16.setBackground(new java.awt.Color(242, 240, 240));
        e8_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e8_t16.setText("Equipo n° 8");
        e8_t16.setMaximumSize(new java.awt.Dimension(86, 28));
        e8_t16.setMinimumSize(new java.awt.Dimension(86, 28));
        e8_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e8_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e8_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 86, 28));

        octavo_a.setEditable(false);
        octavo_a.setBackground(new java.awt.Color(242, 240, 240));
        octavo_a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_a.setText("Ganador 8° a");
        octavo_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_aActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(octavo_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 86, 28));

        octavo_b.setEditable(false);
        octavo_b.setBackground(new java.awt.Color(242, 240, 240));
        octavo_b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_b.setText("Ganador 8° b");
        octavo_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_bActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(octavo_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 86, 28));

        octavo_c.setEditable(false);
        octavo_c.setBackground(new java.awt.Color(242, 240, 240));
        octavo_c.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_c.setText("Ganador 8° c");
        octavo_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_cActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(octavo_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 86, 28));

        octavo_d.setEditable(false);
        octavo_d.setBackground(new java.awt.Color(242, 240, 240));
        octavo_d.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_d.setText("Ganador 8° d");
        octavo_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_dActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(octavo_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 86, 28));

        semi_a_t16.setEditable(false);
        semi_a_t16.setBackground(new java.awt.Color(242, 240, 240));
        semi_a_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semi_a_t16.setText("Ganador 4° a");
        semi_a_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semi_a_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(semi_a_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 86, 28));

        final1_t16.setEditable(false);
        final1_t16.setBackground(new java.awt.Color(242, 240, 240));
        final1_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        final1_t16.setText("Finalista 1");
        final1_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                final1_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(final1_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 86, 28));

        final2_t16.setEditable(false);
        final2_t16.setBackground(new java.awt.Color(242, 240, 240));
        final2_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        final2_t16.setText("Finalista 2");
        final2_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                final2_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(final2_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 86, 28));

        final_lbl_t16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        final_lbl_t16.setText("FINAL");
        torneo16_frame.getContentPane().add(final_lbl_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 110, -1));

        tyc_2_t16.setEditable(false);
        tyc_2_t16.setBackground(new java.awt.Color(242, 240, 240));
        tyc_2_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tyc_2_t16.setText("3y4 b");
        tyc_2_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyc_2_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(tyc_2_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 86, 28));

        tyc_1_t16.setEditable(false);
        tyc_1_t16.setBackground(new java.awt.Color(242, 240, 240));
        tyc_1_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tyc_1_t16.setText("3y4 a");
        tyc_1_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyc_1_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(tyc_1_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 86, 28));

        tyc_lbl_t16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tyc_lbl_t16.setText("3er y 4to");
        torneo16_frame.getContentPane().add(tyc_lbl_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 110, -1));

        semi_b_t16.setEditable(false);
        semi_b_t16.setBackground(new java.awt.Color(242, 240, 240));
        semi_b_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semi_b_t16.setText("Ganador 4° b");
        semi_b_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semi_b_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(semi_b_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 86, 28));

        b8c_t16.setText("=");
        b8c_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8c_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b8c_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 50, -1));

        b8a_t16.setText("=");
        b8a_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8a_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b8a_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 50, -1));
        torneo16_frame.getContentPane().add(re1_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 30, -1));
        torneo16_frame.getContentPane().add(re3_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 30, -1));
        torneo16_frame.getContentPane().add(re4_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 30, -1));
        torneo16_frame.getContentPane().add(re2_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 30, -1));
        torneo16_frame.getContentPane().add(re5_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 30, -1));
        torneo16_frame.getContentPane().add(re6_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 30, -1));

        b8b_t16.setText("=");
        b8b_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8b_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b8b_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, -1));
        torneo16_frame.getContentPane().add(re7_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 30, -1));
        torneo16_frame.getContentPane().add(re8_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 30, -1));

        b8d_t16.setText("=");
        b8d_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8d_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b8d_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 50, -1));

        r_8a_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8a_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_8a_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 30, -1));

        r_8b_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8b_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_8b_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 30, -1));

        r_8d_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8d_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_8d_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 30, -1));

        r_8c_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8c_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_8c_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 30, -1));

        b_4b_16.setText("=");
        b_4b_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4b_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b_4b_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 40, -1));

        b_4a_16.setText("=");
        b_4a_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4a_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b_4a_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 40, -1));

        bsemi_a_t16.setText("=");
        bsemi_a_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsemi_a_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(bsemi_a_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 50, -1));

        r_semib_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_semib_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_semib_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 30, -1));

        r_semia_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_semia_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_semia_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 30, -1));

        r_tyc_2_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_tyc_2_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_tyc_2_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 30, -1));

        r_final2_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_final2_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_final2_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 30, -1));

        b_tyc_t16.setText("=");
        b_tyc_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tyc_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b_tyc_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 50, -1));

        e9_t16.setEditable(false);
        e9_t16.setBackground(new java.awt.Color(242, 240, 240));
        e9_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e9_t16.setText("Equipo n° 9");
        e9_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e9_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e9_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 86, 28));

        e10_t16.setEditable(false);
        e10_t16.setBackground(new java.awt.Color(242, 240, 240));
        e10_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e10_t16.setText("Equipo n 10");
        e10_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e10_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e10_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 40, 86, 28));

        e11_t16.setEditable(false);
        e11_t16.setBackground(new java.awt.Color(242, 240, 240));
        e11_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e11_t16.setText("Equipo n 11");
        e11_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e11_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e11_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 80, 86, 28));

        e12_t16.setEditable(false);
        e12_t16.setBackground(new java.awt.Color(242, 240, 240));
        e12_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e12_t16.setText("Equipo n 12");
        e12_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e12_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e12_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 110, 86, 28));

        e13_t16.setEditable(false);
        e13_t16.setBackground(new java.awt.Color(242, 240, 240));
        e13_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e13_t16.setText("Equipo n 13");
        e13_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e13_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e13_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 150, 86, 28));

        e14_t16.setEditable(false);
        e14_t16.setBackground(new java.awt.Color(242, 240, 240));
        e14_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e14_t16.setText("Equipo n 14");
        e14_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e14_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e14_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 180, 86, 28));

        e15_t16.setEditable(false);
        e15_t16.setBackground(new java.awt.Color(242, 240, 240));
        e15_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e15_t16.setText("Equipo n 15");
        e15_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e15_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e15_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 220, 86, 28));

        e16_t16.setEditable(false);
        e16_t16.setBackground(new java.awt.Color(242, 240, 240));
        e16_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e16_t16.setText("Equipo n 16");
        e16_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e16_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(e16_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 250, 86, 28));

        octavo_e.setEditable(false);
        octavo_e.setBackground(new java.awt.Color(242, 240, 240));
        octavo_e.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_e.setText("Ganador 8° e");
        octavo_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_eActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(octavo_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 86, 28));

        octavo_f.setEditable(false);
        octavo_f.setBackground(new java.awt.Color(242, 240, 240));
        octavo_f.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_f.setText("Ganador 8° f");
        octavo_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_fActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(octavo_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 100, 86, 28));

        octavo_g.setEditable(false);
        octavo_g.setBackground(new java.awt.Color(242, 240, 240));
        octavo_g.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_g.setText("Ganador 8° g");
        octavo_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_gActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(octavo_g, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 160, 86, 28));

        octavo_h.setEditable(false);
        octavo_h.setBackground(new java.awt.Color(242, 240, 240));
        octavo_h.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_h.setText("Ganador 8° h");
        octavo_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_hActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(octavo_h, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 230, 86, 28));

        semi_c_t16.setEditable(false);
        semi_c_t16.setBackground(new java.awt.Color(242, 240, 240));
        semi_c_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semi_c_t16.setText("Ganador 4° c");
        semi_c_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semi_c_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(semi_c_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 86, 28));

        semi_d_t16.setEditable(false);
        semi_d_t16.setBackground(new java.awt.Color(242, 240, 240));
        semi_d_t16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semi_d_t16.setText("Ganador 4° d");
        semi_d_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semi_d_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(semi_d_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 190, 86, 28));

        b8g_t16.setText("=");
        b8g_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8g_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b8g_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 160, 50, -1));

        b8e_t16.setText("=");
        b8e_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8e_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b8e_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, 50, -1));
        torneo16_frame.getContentPane().add(re9_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 30, -1));
        torneo16_frame.getContentPane().add(re11_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 80, 30, -1));
        torneo16_frame.getContentPane().add(re12_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 110, 30, -1));
        torneo16_frame.getContentPane().add(re10_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 40, 30, -1));
        torneo16_frame.getContentPane().add(re13_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 150, 30, -1));
        torneo16_frame.getContentPane().add(re14_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 180, 30, -1));

        b8f_t16.setText("=");
        b8f_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8f_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b8f_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 100, 50, -1));
        torneo16_frame.getContentPane().add(re15_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 220, 30, -1));
        torneo16_frame.getContentPane().add(re16_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 250, 30, -1));

        b8h_t16.setText("=");
        b8h_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8h_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b8h_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 230, 50, -1));

        r_8e_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8e_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_8e_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 30, -1));

        r_semic_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_semic_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_semic_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 30, -1));

        r_8h_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8h_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_8h_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 230, 30, -1));

        b_4c_16.setText("=");
        b_4c_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4c_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b_4c_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 40, -1));

        b_final_t16.setText("=");
        b_final_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_final_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b_final_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 50, -1));

        r_8g_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8g_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_8g_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, 30, -1));

        r_8f_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8f_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_8f_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 100, 30, -1));

        r_semid_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_semid_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_semid_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 30, -1));

        torneo_lbl1.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 24)); // NOI18N
        torneo_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        torneo_lbl1.setText("-_-");
        torneo16_frame.getContentPane().add(torneo_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 720, 40));

        bsemi_b_t16.setText("=");
        bsemi_b_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsemi_b_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(bsemi_b_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 50, -1));

        b_4d_16.setText("=");
        b_4d_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4d_16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(b_4d_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 40, -1));

        r_final1_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_final1_t17ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_final1_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 30, -1));

        r_tyc_1_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_tyc_1_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(r_tyc_1_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 30, -1));

        volver_t16.setText("VOLVER");
        volver_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volver_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(volver_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 90, 40));

        salir_t16.setText("SALIR");
        salir_t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_t16ActionPerformed(evt);
            }
        });
        torneo16_frame.getContentPane().add(salir_t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 90, 40));

        tercerpuesto16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tercerpuesto16.setText("-");
        torneo16_frame.getContentPane().add(tercerpuesto16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 330, -1));

        jFrame1.setMaximumSize(new java.awt.Dimension(370, 370));
        jFrame1.setMinimumSize(new java.awt.Dimension(370, 370));
        jFrame1.setPreferredSize(new java.awt.Dimension(370, 370));
        jFrame1.setResizable(false);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("1°");
        jFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        n1_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1_16ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(n1_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 112, -1));
        jFrame1.getContentPane().add(n2_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 112, -1));
        jFrame1.getContentPane().add(n3_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 112, -1));
        jFrame1.getContentPane().add(n4_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 112, -1));
        jFrame1.getContentPane().add(n5_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 112, -1));
        jFrame1.getContentPane().add(n6_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 112, -1));
        jFrame1.getContentPane().add(n7_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 112, -1));
        jFrame1.getContentPane().add(n8_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 112, -1));

        aceptar_n16.setBackground(new java.awt.Color(51, 51, 255));
        aceptar_n16.setText("Aceptar");
        aceptar_n16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_n16ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(aceptar_n16, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 318, 160, -1));

        lbl_nombres16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nombres16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nombres16.setText("Ingresar nombres de los equipos");
        jFrame1.getContentPane().add(lbl_nombres16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 355, 40));

        jLabel19.setText("2°");
        jFrame1.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel20.setText("3°");
        jFrame1.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel21.setText("4°");
        jFrame1.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel22.setText("5°");
        jFrame1.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel23.setText("6°");
        jFrame1.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel24.setText("7°");
        jFrame1.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel25.setText("8°");
        jFrame1.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        volver_n16.setText("Volver");
        jFrame1.getContentPane().add(volver_n16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 81, -1));

        salir_n16.setText("Salir");
        jFrame1.getContentPane().add(salir_n16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 93, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("(El orden  será aleatorio al crearse el torneo)");
        jFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 355, -1));

        jLabel3.setText("9°");
        jFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));
        jFrame1.getContentPane().add(n9_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 112, -1));
        jFrame1.getContentPane().add(n10_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 112, -1));
        jFrame1.getContentPane().add(n11_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 112, -1));
        jFrame1.getContentPane().add(n12_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 112, -1));
        jFrame1.getContentPane().add(n13_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 112, -1));
        jFrame1.getContentPane().add(n14_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 112, -1));

        n15_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n15_16ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(n15_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 112, -1));

        n16_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n16_16ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(n16_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 112, -1));

        jLabel34.setText("10°");
        jFrame1.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel35.setText("11°");
        jFrame1.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel36.setText("12°");
        jFrame1.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel37.setText("13°");
        jFrame1.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel38.setText("14°");
        jFrame1.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel39.setText("15°");
        jFrame1.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel40.setText("16°");
        jFrame1.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        nombreganador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreganador.setText("tuvieja");
        nombreganador.setMaximumSize(new java.awt.Dimension(320, 70));
        nombreganador.setMinimumSize(new java.awt.Dimension(320, 70));
        nombreganador.setPreferredSize(new java.awt.Dimension(320, 70));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Estadisticas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Ganador16Layout = new javax.swing.GroupLayout(Ganador16.getContentPane());
        Ganador16.getContentPane().setLayout(Ganador16Layout);
        Ganador16Layout.setHorizontalGroup(
            Ganador16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ganador16Layout.createSequentialGroup()
                .addComponent(nombreganador, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ganador16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        Ganador16Layout.setVerticalGroup(
            Ganador16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ganador16Layout.createSequentialGroup()
                .addComponent(nombreganador, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Ganador16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton4.setText("Aceptar");

        jLabel4.setText("jLabel4");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(304, 304, 304))
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGap(38, 38, 38)))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGap(52, 52, 52)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Organizador de Torneos");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(88, 7, 14));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        titulo_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_lbl.setText("Organizador de Torneos");
        titulo_lbl.setToolTipText("");

        salir_btn.setText("Salir");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });

        nuevo_btn.setText("Nuevo");
        nuevo_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(titulo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(nuevo_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir_btn)
                .addGap(78, 78, 78))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed

        this.dispose();

    }//GEN-LAST:event_salir_btnActionPerformed

    private void qant_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qant_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qant_boxActionPerformed

    private void nuevo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_btnActionPerformed

        this.dispose();
        nuevo_frame.setVisible(true);
        nuevo_frame.setLocationRelativeTo(null);

        

        // TODO add your handling code here:
    }//GEN-LAST:event_nuevo_btnActionPerformed

    private void volver_btn_f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_btn_f2ActionPerformed

        nuevo_frame.dispose();
        this.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_volver_btn_f2ActionPerformed

    private void salir_btn_f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btn_f2ActionPerformed

        nuevo_frame.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_salir_btn_f2ActionPerformed

    private void nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_txtActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_txtActionPerformed

    private void indiv_rbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiv_rbttnActionPerformed

        lbl2_f2.setText("Cantidad de jugadores:");

        // TODO add your handling code here:
    }//GEN-LAST:event_indiv_rbttnActionPerformed

    private void indiv_rbttnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_indiv_rbttnFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_indiv_rbttnFocusGained

    private void grups_rbttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grups_rbttnActionPerformed

        lbl2_f2.setText("Cantidad de equipos:");

    }//GEN-LAST:event_grups_rbttnActionPerformed

    private void comenzar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzar_btnActionPerformed

        if (qant_box.getSelectedItem() == "16") {
        
        
        
        if (indiv_rbttn.isSelected() && nombre_txt.getText() != null && deporte_txt.getText() != null) {

            nuevo_frame.dispose();
            lbl_nombres16.setText("Ingresa los nombres de los jugadores");
            jFrame1.setVisible(true);
            jFrame1.setLocationRelativeTo(null);
            torneo_lbl1.setText("Torneo " + " individual de " + deporte_txt.getText() + ": “" + nombre_txt.getText() + "”");

        } else if (grups_rbttn.isSelected() && nombre_txt.getText() != null && deporte_txt.getText() != null) {
            nuevo_frame.dispose();
            jFrame1.setVisible(true);
            jFrame1.setLocationRelativeTo(null);
            torneo_lbl1.setText("Torneo " + " en equipos de " + deporte_txt.getText() + ": “" + nombre_txt.getText() + "”");
        } else {

        }

        }
        
        else if (qant_box.getSelectedItem() == "8") {
        
            new Torneo8().setVisible(true);
            
            
            
            
        }
        
    }//GEN-LAST:event_comenzar_btnActionPerformed

    private void deporte_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deporte_txtActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_deporte_txtActionPerformed

    private void tyc_1_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyc_1_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyc_1_t16ActionPerformed

    private void tyc_2_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyc_2_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyc_2_t16ActionPerformed

    private void final2_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_final2_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_final2_t16ActionPerformed

    private void final1_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_final1_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_final1_t16ActionPerformed

    private void semi_a_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semi_a_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semi_a_t16ActionPerformed

    private void octavo_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_dActionPerformed

    private void octavo_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_cActionPerformed

    private void octavo_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_bActionPerformed

    private void octavo_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_aActionPerformed

    private void e8_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e8_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e8_t16ActionPerformed

    private void e7_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e7_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e7_t16ActionPerformed

    private void e6_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e6_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e6_t16ActionPerformed

    private void e5_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e5_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e5_t16ActionPerformed

    private void e4_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e4_t16ActionPerformed

    private void e3_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e3_t16ActionPerformed

    private void e2_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2_t16ActionPerformed

    private void e1_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1_t16ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_e1_t16ActionPerformed

    private void semi_b_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semi_b_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semi_b_t16ActionPerformed

    private void r_8a_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8a_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8a_16ActionPerformed

    private void r_8b_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8b_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8b_16ActionPerformed

    private void r_8d_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8d_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8d_16ActionPerformed

    private void r_8c_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8c_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8c_16ActionPerformed

    private void r_semib_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_semib_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_semib_t16ActionPerformed

    private void r_semia_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_semia_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_semia_t16ActionPerformed

    private void r_tyc_2_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_tyc_2_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_tyc_2_t16ActionPerformed

    private void r_final2_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_final2_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_final2_t16ActionPerformed

    private void e9_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e9_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e9_t16ActionPerformed

    private void e10_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e10_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e10_t16ActionPerformed

    private void e11_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e11_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e11_t16ActionPerformed

    private void e12_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e12_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e12_t16ActionPerformed

    private void e13_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e13_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e13_t16ActionPerformed

    private void e14_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e14_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e14_t16ActionPerformed

    private void e15_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e15_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e15_t16ActionPerformed

    private void e16_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e16_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e16_t16ActionPerformed

    private void octavo_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_eActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_eActionPerformed

    private void octavo_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_fActionPerformed

    private void octavo_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_gActionPerformed

    private void octavo_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_hActionPerformed
        // TODO add your handling c ();();();();vvvvod();e here:
    }//GEN-LAST:event_octavo_hActionPerformed

    private void semi_c_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semi_c_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semi_c_t16ActionPerformed

    private void semi_d_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semi_d_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semi_d_t16ActionPerformed

    private void r_8e_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8e_16ActionPerformed
        // TODO add TU MAMA your handling code here:
    }//GEN-LAST:event_r_8e_16ActionPerformed

    private void r_semic_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_semic_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_semic_t16ActionPerformed


    private void r_8h_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8h_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8h_16ActionPerformed

    private void r_8g_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8g_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8g_16ActionPerformed

    private void r_8f_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8f_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8f_16ActionPerformed

    private void r_semid_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_semid_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_semid_t16ActionPerformed

    private void r_final1_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_final1_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_final1_t17ActionPerformed

    private void r_tyc_1_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_tyc_1_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_tyc_1_t16ActionPerformed

    private void salir_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_t16ActionPerformed

        torneo16_frame.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_salir_t16ActionPerformed

    private void volver_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volver_t16ActionPerformed

        torneo16_frame.setVisible(false);
        this.setVisible(true);


    }//GEN-LAST:event_volver_t16ActionPerformed

    private void shuffleArray(String[] ar) {
        // If running on Java 6 or older, use `new Random()` on RHS here
        Random rnd = ThreadLocalRandom.current();
        for (int i = ar.length - 1; i > 0; i--) {
            int index = rnd.nextInt(i + 1);
            // Simple swap
            String a = ar[index];
            ar[index] = ar[i];
            ar[i] = a;
        }
    }


    private void aceptar_n16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_n16ActionPerformed

        jFrame1.dispose();
        torneo16_frame.setVisible(true);

        String[] solutionArray = {n1_16.getText(),
            n2_16.getText(),
            n3_16.getText(),
            n4_16.getText(),
            n5_16.getText(),
            n6_16.getText(),
            n7_16.getText(),
            n8_16.getText(),
            n9_16.getText(),
            n10_16.getText(),
            n11_16.getText(),
            n12_16.getText(),
            n13_16.getText(),
            n14_16.getText(),
            n15_16.getText(),
            n16_16.getText()};

        shuffleArray(solutionArray);
        
        JTextField[] equipos = { e1_t16, e2_t16, e3_t16, e4_t16, e5_t16, e6_t16, e7_t16, e8_t16, e9_t16, e10_t16, e11_t16, e12_t16, e13_t16, e14_t16, e15_t16, e16_t16 };
        
        for (int i = 0; i < solutionArray.length; i++) {
            equipos[i].setText(solutionArray[i]);
        }
        
        
    }//GEN-LAST:event_aceptar_n16ActionPerformed


    private void n1_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1_16ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_n1_16ActionPerformed

    private void n16_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n16_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n16_16ActionPerformed

    private void n15_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n15_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n15_16ActionPerformed

    private void b8a_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8a_t16ActionPerformed

        if (Integer.valueOf(re1_t16.getText()) > Integer.valueOf(re2_t16.getText())) {

            octavo_a.setText(e1_t16.getText()); }
            
            else {    octavo_a.setText(e2_t16.getText());}
                    

    }//GEN-LAST:event_b8a_t16ActionPerformed

    private void b8b_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8b_t16ActionPerformed

     if (Integer.valueOf(re3_t16.getText()) > Integer.valueOf(re4_t16.getText())) {

            octavo_b.setText(e3_t16.getText()); }
            
            else {    octavo_b.setText(e4_t16.getText());}
                    

      


    }//GEN-LAST:event_b8b_t16ActionPerformed

    private void b8c_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8c_t16ActionPerformed

        if (Integer.valueOf(re6_t16.getText()) > Integer.valueOf(re5_t16.getText())) {

            octavo_c.setText(e5_t16.getText()); }
            
            else {    octavo_c.setText(e6_t16.getText());}
                    



    }//GEN-LAST:event_b8c_t16ActionPerformed

    private void b8d_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8d_t16ActionPerformed


      if (Integer.valueOf(re7_t16.getText()) > Integer.valueOf(re8_t16.getText())) {

            octavo_d.setText(e7_t16.getText()); }
            
            else {    octavo_d.setText(e8_t16.getText());}


    }//GEN-LAST:event_b8d_t16ActionPerformed

    private void b8e_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8e_t16ActionPerformed

           if (Integer.valueOf(re9_t16.getText()) > Integer.valueOf(re10_t16.getText())) {

            octavo_e.setText(e9_t16.getText()); }
            
            else {    octavo_e.setText(e10_t16.getText());}




        // TODO add your handling code here:
    }//GEN-LAST:event_b8e_t16ActionPerformed

    private void b8f_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8f_t16ActionPerformed
        
      if (Integer.valueOf(re11_t16.getText()) > Integer.valueOf(re12_t16.getText())) {

            octavo_f.setText(e11_t16.getText()); }
            
            else {    octavo_f.setText(e12_t16.getText());}





// TODO add your handling code here:
    }//GEN-LAST:event_b8f_t16ActionPerformed

    private void b8g_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8g_t16ActionPerformed

         if (Integer.valueOf(re13_t16.getText()) > Integer.valueOf(re14_t16.getText())) {

            octavo_g.setText(e13_t16.getText()); }
            
            else {    octavo_g.setText(e14_t16.getText());}




        // TODO add your handling code here:
    }//GEN-LAST:event_b8g_t16ActionPerformed

    private void b8h_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8h_t16ActionPerformed


        if (Integer.valueOf(re15_t16.getText()) > Integer.valueOf(re16_t16.getText())) {

            octavo_h.setText(e15_t16.getText()); }
            
            else {    octavo_h.setText(e16_t16.getText());}




        // TODO add your handling code here:
    }//GEN-LAST:event_b8h_t16ActionPerformed

    private void b_4a_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4a_16ActionPerformed

             if (Integer.valueOf(r_8a_16.getText()) > Integer.valueOf(r_8b_16.getText())) {

            semi_a_t16.setText(octavo_a.getText()); }
            
            else {    semi_a_t16.setText(octavo_b.getText());}

    
            



    }//GEN-LAST:event_b_4a_16ActionPerformed

    private void bsemi_a_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsemi_a_t16ActionPerformed

           if (Integer.valueOf(r_semia_t16.getText()) > Integer.valueOf(r_semib_t16.getText())) {

            final1_t16.setText(semi_a_t16.getText()); 
            tyc_1_t16.setText(semi_b_t16.getText());}
            
            else {    final1_t16.setText(semi_b_t16.getText());
                    tyc_1_t16.setText(semi_a_t16.getText());}


        




    }//GEN-LAST:event_bsemi_a_t16ActionPerformed

    private void b_4b_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4b_16ActionPerformed

    if (Integer.valueOf(r_8c_16.getText()) > Integer.valueOf(r_8d_16.getText())) {

            semi_b_t16.setText(octavo_c.getText()); }
            
            else {    semi_b_t16.setText(octavo_d.getText());}

    

    }//GEN-LAST:event_b_4b_16ActionPerformed

    private void b_4c_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4c_16ActionPerformed

         if (Integer.valueOf(r_8e_16.getText()) > Integer.valueOf(r_8f_16.getText())) {

            semi_c_t16.setText(octavo_e.getText()); }
            
            else {    semi_c_t16.setText(octavo_f.getText());}




    }//GEN-LAST:event_b_4c_16ActionPerformed

    private void b_4d_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4d_16ActionPerformed

         if (Integer.valueOf(r_8g_16.getText()) > Integer.valueOf(r_8h_16.getText())) {

            semi_d_t16.setText(octavo_g.getText()); 
           }
            
            else {    semi_d_t16.setText(octavo_h.getText());}




    }//GEN-LAST:event_b_4d_16ActionPerformed

    private void bsemi_b_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsemi_b_t16ActionPerformed


         if (Integer.valueOf(r_semic_t16.getText()) > Integer.valueOf(r_semid_t16.getText())) {

            final2_t16.setText(semi_c_t16.getText());
            tyc_2_t16.setText(semi_d_t16.getText()); }
            
            else {    final2_t16.setText(semi_c_t16.getText());
                       tyc_2_t16.setText(semi_d_t16.getText());
                            }


        


    }//GEN-LAST:event_bsemi_b_t16ActionPerformed

    private void b_tyc_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tyc_t16ActionPerformed

     if (Integer.valueOf(r_tyc_1_t16.getText()) > Integer.valueOf(r_tyc_2_t16.getText())) {

            tercerpuesto16.setText("Tercer puesto: " + tyc_1_t16.getText());
            }
            
            else {       tercerpuesto16.setText("Tercer puesto: " + tyc_2_t16.getText());
                            }


    }//GEN-LAST:event_b_tyc_t16ActionPerformed

    private void b_final_t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_final_t16ActionPerformed

        Ganador16.setVisible(true);
        Ganador16.setLocationRelativeTo(null);
        Ganador16.setSize(521, 183);
        if (Integer.valueOf(r_final1_t17.getText())> Integer.valueOf(r_final2_t16.getText())) {
               
            nombreganador.setText("Ganador: " + final1_t16.getText());}
        else {
            
            nombreganador.setText("Ganador: " + final2_t16.getText());
            
        }
    }//GEN-LAST:event_b_final_t16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        torneo16_frame.dispose();
        Ganador16.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Ganador16.setVisible(false);
       
             


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(null);
        jLabel4.setText("\n Ganador: " + final1_t16 + "\n Segundo Puesto: " + final2_t16);




    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Torneo16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Torneo16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Torneo16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Torneo16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Torneo16().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Ganador16;
    private javax.swing.JButton aceptar_n16;
    private javax.swing.JButton b8a_t16;
    private javax.swing.JButton b8b_t16;
    private javax.swing.JButton b8c_t16;
    private javax.swing.JButton b8d_t16;
    private javax.swing.JButton b8e_t16;
    private javax.swing.JButton b8f_t16;
    private javax.swing.JButton b8g_t16;
    private javax.swing.JButton b8h_t16;
    private javax.swing.JButton b_4a_16;
    private javax.swing.JButton b_4b_16;
    private javax.swing.JButton b_4c_16;
    private javax.swing.JButton b_4d_16;
    private javax.swing.JButton b_final_t16;
    private javax.swing.JButton b_tyc_t16;
    private javax.swing.JButton bsemi_a_t16;
    private javax.swing.JButton bsemi_b_t16;
    private javax.swing.JButton comenzar_btn;
    private javax.swing.JTextField deporte_txt;
    private javax.swing.JTextField e10_t16;
    private javax.swing.JTextField e11_t16;
    private javax.swing.JTextField e12_t16;
    private javax.swing.JTextField e13_t16;
    private javax.swing.JTextField e14_t16;
    private javax.swing.JTextField e15_t16;
    private javax.swing.JTextField e16_t16;
    private javax.swing.JTextField e1_t16;
    private javax.swing.JTextField e2_t16;
    private javax.swing.JTextField e3_t16;
    private javax.swing.JTextField e4_t16;
    private javax.swing.JTextField e5_t16;
    private javax.swing.JTextField e6_t16;
    private javax.swing.JTextField e7_t16;
    private javax.swing.JTextField e8_t16;
    private javax.swing.JTextField e9_t16;
    private javax.swing.ButtonGroup filtro;
    private javax.swing.JTextField final1_t16;
    private javax.swing.JTextField final2_t16;
    private javax.swing.JLabel final_lbl_t16;
    private javax.swing.JRadioButton grups_rbttn;
    private javax.swing.JRadioButton indiv_rbttn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1_f2;
    private javax.swing.JLabel lbl2_f2;
    private javax.swing.JLabel lbl3_f2;
    private javax.swing.JLabel lbl4_f3;
    private javax.swing.JLabel lbl_nombres16;
    private javax.swing.JTextField n10_16;
    private javax.swing.JTextField n11_16;
    private javax.swing.JTextField n12_16;
    private javax.swing.JTextField n13_16;
    private javax.swing.JTextField n14_16;
    private javax.swing.JTextField n15_16;
    private javax.swing.JTextField n16_16;
    private javax.swing.JTextField n1_16;
    private javax.swing.JTextField n2_16;
    private javax.swing.JTextField n3_16;
    private javax.swing.JTextField n4_16;
    private javax.swing.JTextField n5_16;
    private javax.swing.JTextField n6_16;
    private javax.swing.JTextField n7_16;
    private javax.swing.JTextField n8_16;
    private javax.swing.JTextField n9_16;
    private javax.swing.JTextField nombre_txt;
    private javax.swing.JLabel nombreganador;
    private javax.swing.JButton nuevo_btn;
    private javax.swing.JFrame nuevo_frame;
    private javax.swing.JTextField octavo_a;
    private javax.swing.JTextField octavo_b;
    private javax.swing.JTextField octavo_c;
    private javax.swing.JTextField octavo_d;
    private javax.swing.JTextField octavo_e;
    private javax.swing.JTextField octavo_f;
    private javax.swing.JTextField octavo_g;
    private javax.swing.JTextField octavo_h;
    private javax.swing.JComboBox<String> qant_box;
    private javax.swing.JTextField r_8a_16;
    private javax.swing.JTextField r_8b_16;
    private javax.swing.JTextField r_8c_16;
    private javax.swing.JTextField r_8d_16;
    private javax.swing.JTextField r_8e_16;
    private javax.swing.JTextField r_8f_16;
    private javax.swing.JTextField r_8g_16;
    private javax.swing.JTextField r_8h_16;
    private javax.swing.JTextField r_final1_t17;
    private javax.swing.JTextField r_final2_t16;
    private javax.swing.JTextField r_semia_t16;
    private javax.swing.JTextField r_semib_t16;
    private javax.swing.JTextField r_semic_t16;
    private javax.swing.JTextField r_semid_t16;
    private javax.swing.JTextField r_tyc_1_t16;
    private javax.swing.JTextField r_tyc_2_t16;
    private javax.swing.JTextField re10_t16;
    private javax.swing.JTextField re11_t16;
    private javax.swing.JTextField re12_t16;
    private javax.swing.JTextField re13_t16;
    private javax.swing.JTextField re14_t16;
    private javax.swing.JTextField re15_t16;
    private javax.swing.JTextField re16_t16;
    private javax.swing.JTextField re1_t16;
    private javax.swing.JTextField re2_t16;
    private javax.swing.JTextField re3_t16;
    private javax.swing.JTextField re4_t16;
    private javax.swing.JTextField re5_t16;
    private javax.swing.JTextField re6_t16;
    private javax.swing.JTextField re7_t16;
    private javax.swing.JTextField re8_t16;
    private javax.swing.JTextField re9_t16;
    private javax.swing.JButton salir_btn;
    private javax.swing.JButton salir_btn_f2;
    private javax.swing.JButton salir_n16;
    private javax.swing.JButton salir_t16;
    private javax.swing.JTextField semi_a_t16;
    private javax.swing.JTextField semi_b_t16;
    private javax.swing.JTextField semi_c_t16;
    private javax.swing.JTextField semi_d_t16;
    private javax.swing.JLabel tercerpuesto16;
    private javax.swing.JLabel titulo_lbl;
    private javax.swing.JFrame torneo16_frame;
    private javax.swing.JLabel torneo_lbl1;
    private javax.swing.JTextField tyc_1_t16;
    private javax.swing.JTextField tyc_2_t16;
    private javax.swing.JLabel tyc_lbl_t16;
    private javax.swing.JButton volver_btn_f2;
    private javax.swing.JButton volver_n16;
    private javax.swing.JButton volver_t16;
    // End of variables declaration//GEN-END:variables
}
