/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JTextField;

/**
 *
 * @author nacho
 */
public class Torneo8 extends javax.swing.JFrame {

    /**
     * Creates new form Torneo8
     */
    public Torneo8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        e1_t17 = new javax.swing.JTextField();
        e2_t17 = new javax.swing.JTextField();
        e3_t17 = new javax.swing.JTextField();
        e4_t17 = new javax.swing.JTextField();
        octavo_a1 = new javax.swing.JTextField();
        octavo_b1 = new javax.swing.JTextField();
        semi_a_t17 = new javax.swing.JTextField();
        b8a_t17 = new javax.swing.JButton();
        re1_t17 = new javax.swing.JTextField();
        re3_t17 = new javax.swing.JTextField();
        re4_t17 = new javax.swing.JTextField();
        re2_t17 = new javax.swing.JTextField();
        b8b_t17 = new javax.swing.JButton();
        r_8a_17 = new javax.swing.JTextField();
        r_8b_17 = new javax.swing.JTextField();
        b_4a_17 = new javax.swing.JButton();
        r_semia_t18 = new javax.swing.JTextField();
        torneo_lbl3 = new javax.swing.JLabel();
        e9_t17 = new javax.swing.JTextField();
        e10_t17 = new javax.swing.JTextField();
        e11_t17 = new javax.swing.JTextField();
        e12_t17 = new javax.swing.JTextField();
        octavo_e1 = new javax.swing.JTextField();
        octavo_f1 = new javax.swing.JTextField();
        semi_c_t17 = new javax.swing.JTextField();
        b8e_t17 = new javax.swing.JButton();
        re9_t17 = new javax.swing.JTextField();
        re11_t17 = new javax.swing.JTextField();
        re12_t17 = new javax.swing.JTextField();
        re10_t17 = new javax.swing.JTextField();
        b8f_t17 = new javax.swing.JButton();
        r_8e_17 = new javax.swing.JTextField();
        b_4c_18 = new javax.swing.JButton();
        r_8f_17 = new javax.swing.JTextField();
        r_semia_t19 = new javax.swing.JTextField();
        b_4c_19 = new javax.swing.JButton();
        tyc_2_t17 = new javax.swing.JTextField();
        tyc_1_t17 = new javax.swing.JTextField();
        LaReConchaDeSuMadre1 = new javax.swing.JLabel();
        r_tyc_2_t17 = new javax.swing.JTextField();
        b_tyc_t17 = new javax.swing.JButton();
        r_tyc_1_t17 = new javax.swing.JTextField();
        tyc_lbl_t18 = new javax.swing.JLabel();
        tercerpuesto17 = new javax.swing.JLabel();
        n7_16 = new javax.swing.JTextField();
        n1_16 = new javax.swing.JTextField();
        n4_16 = new javax.swing.JTextField();
        aceptar_n16 = new javax.swing.JButton();
        salir_n16 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        n2_16 = new javax.swing.JTextField();
        n6_16 = new javax.swing.JTextField();
        n3_16 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        volver_n16 = new javax.swing.JButton();
        lbl_nombres16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        n5_16 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        n8_16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        e1_t17.setEditable(false);
        e1_t17.setBackground(new java.awt.Color(242, 240, 240));
        e1_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e1_t17.setText("Equipo n° 1");
        e1_t17.setMaximumSize(new java.awt.Dimension(86, 28));
        e1_t17.setMinimumSize(new java.awt.Dimension(86, 28));
        e1_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(e1_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 86, 28));

        e2_t17.setEditable(false);
        e2_t17.setBackground(new java.awt.Color(242, 240, 240));
        e2_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e2_t17.setText("Equipo n° 2");
        e2_t17.setMaximumSize(new java.awt.Dimension(86, 28));
        e2_t17.setMinimumSize(new java.awt.Dimension(86, 28));
        e2_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(e2_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 86, 28));

        e3_t17.setEditable(false);
        e3_t17.setBackground(new java.awt.Color(242, 240, 240));
        e3_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e3_t17.setText("Equipo n° 3");
        e3_t17.setMaximumSize(new java.awt.Dimension(86, 28));
        e3_t17.setMinimumSize(new java.awt.Dimension(86, 28));
        e3_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(e3_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 86, 28));

        e4_t17.setEditable(false);
        e4_t17.setBackground(new java.awt.Color(242, 240, 240));
        e4_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e4_t17.setText("Equipo n° 4");
        e4_t17.setMaximumSize(new java.awt.Dimension(86, 28));
        e4_t17.setMinimumSize(new java.awt.Dimension(86, 28));
        e4_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(e4_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 86, 28));

        octavo_a1.setEditable(false);
        octavo_a1.setBackground(new java.awt.Color(242, 240, 240));
        octavo_a1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_a1.setText("Ganador 4° a");
        octavo_a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_a1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(octavo_a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 86, 28));

        octavo_b1.setEditable(false);
        octavo_b1.setBackground(new java.awt.Color(242, 240, 240));
        octavo_b1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_b1.setText("Ganador 4° b");
        octavo_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_b1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(octavo_b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 86, 28));

        semi_a_t17.setEditable(false);
        semi_a_t17.setBackground(new java.awt.Color(242, 240, 240));
        semi_a_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semi_a_t17.setText("Ganador 4° a");
        semi_a_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semi_a_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(semi_a_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 110, 28));

        b8a_t17.setText("=");
        b8a_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8a_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(b8a_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 50, -1));
        jFrame1.getContentPane().add(re1_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 30, -1));
        jFrame1.getContentPane().add(re3_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 30, -1));
        jFrame1.getContentPane().add(re4_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 30, -1));
        jFrame1.getContentPane().add(re2_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 30, -1));

        b8b_t17.setText("=");
        b8b_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8b_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(b8b_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 50, -1));

        r_8a_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8a_17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r_8a_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 30, -1));

        r_8b_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8b_17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r_8b_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 30, -1));

        b_4a_17.setText("=");
        b_4a_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4a_17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(b_4a_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 30, -1));

        r_semia_t18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_semia_t18ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r_semia_t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 30, -1));

        torneo_lbl3.setFont(new java.awt.Font("Noto Sans CJK JP Bold", 0, 24)); // NOI18N
        torneo_lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        torneo_lbl3.setText("-_-");
        jFrame1.getContentPane().add(torneo_lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1120, 40));

        e9_t17.setEditable(false);
        e9_t17.setBackground(new java.awt.Color(242, 240, 240));
        e9_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e9_t17.setText("Equipo n° 5");
        e9_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e9_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(e9_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, 86, 28));

        e10_t17.setEditable(false);
        e10_t17.setBackground(new java.awt.Color(242, 240, 240));
        e10_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e10_t17.setText("Equipo n° 6");
        e10_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e10_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(e10_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 90, 86, 28));

        e11_t17.setEditable(false);
        e11_t17.setBackground(new java.awt.Color(242, 240, 240));
        e11_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e11_t17.setText("Equipo n° 7");
        e11_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e11_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(e11_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, 86, 28));

        e12_t17.setEditable(false);
        e12_t17.setBackground(new java.awt.Color(242, 240, 240));
        e12_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        e12_t17.setText("Equipo n° 8");
        e12_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e12_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(e12_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, 86, 28));

        octavo_e1.setEditable(false);
        octavo_e1.setBackground(new java.awt.Color(242, 240, 240));
        octavo_e1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_e1.setText("Ganador 4° c");
        octavo_e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_e1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(octavo_e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 86, 28));

        octavo_f1.setEditable(false);
        octavo_f1.setBackground(new java.awt.Color(242, 240, 240));
        octavo_f1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        octavo_f1.setText("Ganador 4° d");
        octavo_f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octavo_f1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(octavo_f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 86, 28));

        semi_c_t17.setEditable(false);
        semi_c_t17.setBackground(new java.awt.Color(242, 240, 240));
        semi_c_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        semi_c_t17.setText("Ganador 4° c");
        semi_c_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semi_c_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(semi_c_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 110, 28));

        b8e_t17.setText("=");
        b8e_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8e_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(b8e_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 50, -1));
        jFrame1.getContentPane().add(re9_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 30, -1));
        jFrame1.getContentPane().add(re11_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 140, 30, -1));
        jFrame1.getContentPane().add(re12_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 30, -1));
        jFrame1.getContentPane().add(re10_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 30, -1));

        b8f_t17.setText("=");
        b8f_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8f_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(b8f_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 50, -1));

        r_8e_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8e_17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r_8e_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 30, -1));

        b_4c_18.setText("=");
        b_4c_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4c_18ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(b_4c_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 30, -1));

        r_8f_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_8f_17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r_8f_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 30, -1));

        r_semia_t19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_semia_t19ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r_semia_t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 30, -1));

        b_4c_19.setText("=");
        b_4c_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4c_19ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(b_4c_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 30, -1));

        tyc_2_t17.setEditable(false);
        tyc_2_t17.setBackground(new java.awt.Color(242, 240, 240));
        tyc_2_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tyc_2_t17.setText("3y4 b");
        tyc_2_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyc_2_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(tyc_2_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 86, 28));

        tyc_1_t17.setEditable(false);
        tyc_1_t17.setBackground(new java.awt.Color(242, 240, 240));
        tyc_1_t17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tyc_1_t17.setText("3y4 a");
        tyc_1_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyc_1_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(tyc_1_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 86, 28));

        LaReConchaDeSuMadre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LaReConchaDeSuMadre1.setText("FINAL");
        jFrame1.getContentPane().add(LaReConchaDeSuMadre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 110, -1));

        r_tyc_2_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_tyc_2_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r_tyc_2_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 30, -1));

        b_tyc_t17.setText("=");
        b_tyc_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tyc_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(b_tyc_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 50, -1));

        r_tyc_1_t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_tyc_1_t17ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(r_tyc_1_t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 30, -1));

        tyc_lbl_t18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tyc_lbl_t18.setText("3er y 4to");
        jFrame1.getContentPane().add(tyc_lbl_t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 110, -1));

        tercerpuesto17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tercerpuesto17.setText("-");
        jFrame1.getContentPane().add(tercerpuesto17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 330, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(200, 200));
        setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(n7_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 112, -1));

        n1_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1_16ActionPerformed(evt);
            }
        });
        getContentPane().add(n1_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 112, -1));
        getContentPane().add(n4_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 112, -1));

        aceptar_n16.setBackground(new java.awt.Color(51, 51, 255));
        aceptar_n16.setText("Aceptar");
        aceptar_n16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_n16ActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar_n16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 160, -1));

        salir_n16.setText("Salir");
        getContentPane().add(salir_n16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 93, -1));

        jLabel24.setText("7°");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));
        getContentPane().add(n2_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 112, -1));
        getContentPane().add(n6_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 112, -1));
        getContentPane().add(n3_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 112, -1));

        jLabel22.setText("5°");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        volver_n16.setText("Volver");
        getContentPane().add(volver_n16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 81, -1));

        lbl_nombres16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_nombres16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nombres16.setText("Ingresar nombres de los equipos");
        getContentPane().add(lbl_nombres16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 355, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("(El orden  será aleatorio al crearse el torneo)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 355, -1));
        getContentPane().add(n5_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 112, -1));

        jLabel25.setText("8°");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));
        getContentPane().add(n8_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 112, -1));

        jLabel23.setText("6°");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabel19.setText("2°");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel20.setText("3°");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel1.setText("1°");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel21.setText("4°");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e1_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1_t17ActionPerformed

    private void e2_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2_t17ActionPerformed

    private void e3_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e3_t17ActionPerformed

    private void e4_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e4_t17ActionPerformed

    private void octavo_a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_a1ActionPerformed

    private void octavo_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_b1ActionPerformed

    private void semi_a_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semi_a_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semi_a_t17ActionPerformed

    private void b8a_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8a_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8a_t17ActionPerformed

    private void b8b_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8b_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8b_t17ActionPerformed

    private void r_8a_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8a_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8a_17ActionPerformed

    private void r_8b_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8b_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8b_17ActionPerformed

    private void b_4a_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4a_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_4a_17ActionPerformed

    private void r_semia_t18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_semia_t18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_semia_t18ActionPerformed

    private void e9_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e9_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e9_t17ActionPerformed

    private void e10_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e10_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e10_t17ActionPerformed

    private void e11_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e11_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e11_t17ActionPerformed

    private void e12_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e12_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e12_t17ActionPerformed

    private void octavo_e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_e1ActionPerformed

    private void octavo_f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octavo_f1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octavo_f1ActionPerformed

    private void semi_c_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semi_c_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semi_c_t17ActionPerformed

    private void b8e_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8e_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8e_t17ActionPerformed

    private void b8f_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8f_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8f_t17ActionPerformed

    private void r_8e_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8e_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8e_17ActionPerformed

    private void b_4c_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4c_18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_4c_18ActionPerformed

    private void r_8f_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_8f_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_8f_17ActionPerformed

    private void r_semia_t19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_semia_t19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_semia_t19ActionPerformed

    private void b_4c_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4c_19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_4c_19ActionPerformed

    private void tyc_2_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyc_2_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyc_2_t17ActionPerformed

    private void tyc_1_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyc_1_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyc_1_t17ActionPerformed

    private void r_tyc_2_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_tyc_2_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_tyc_2_t17ActionPerformed

    private void b_tyc_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tyc_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_tyc_t17ActionPerformed

    private void r_tyc_1_t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_tyc_1_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_tyc_1_t17ActionPerformed

    private void n1_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1_16ActionPerformed

    private void aceptar_n16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_n16ActionPerformed

        jFrame1.setVisible(true);
        

        String[] solutionArray = {n1_16.getText(),
            n2_16.getText(),
            n3_16.getText(),
            n4_16.getText(),
            n5_16.getText(),
            n6_16.getText(),
            n7_16.getText(),
            n8_16.getText(),
        };

        shuffleArray(solutionArray);

        JTextField[] equipos = { e1_t17, e2_t17, e3_t17, e4_t17, e9_t17, e10_t17, e11_t17, e12_t17  };

        for (int i = 0; i < solutionArray.length; i++) {
            equipos[i].setText(solutionArray[i]);
        }
    }//GEN-LAST:event_aceptar_n16ActionPerformed

        private void shuffleArray(String[] ar) {
        // If running on Java 6 or older, use `new Random()` on RHS here
        Random rnd = ThreadLocalRandom.current();
        for (int i = ar.length - 1; i > 0; i--) {
            int index = rnd.nextInt(i + 1);
            // Simple swap
            String a = ar[index];
            ar[index] = ar[i];
            ar[i] = a;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Torneo8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Torneo8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Torneo8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Torneo8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Torneo8().setVisible(true);         
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LaReConchaDeSuMadre1;
    private javax.swing.JButton aceptar_n16;
    private javax.swing.JButton b8a_t17;
    private javax.swing.JButton b8b_t17;
    private javax.swing.JButton b8e_t17;
    private javax.swing.JButton b8f_t17;
    private javax.swing.JButton b_4a_17;
    private javax.swing.JButton b_4c_18;
    private javax.swing.JButton b_4c_19;
    private javax.swing.JButton b_tyc_t17;
    private javax.swing.JTextField e10_t17;
    private javax.swing.JTextField e11_t17;
    private javax.swing.JTextField e12_t17;
    private javax.swing.JTextField e1_t17;
    private javax.swing.JTextField e2_t17;
    private javax.swing.JTextField e3_t17;
    private javax.swing.JTextField e4_t17;
    private javax.swing.JTextField e9_t17;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel lbl_nombres16;
    private javax.swing.JTextField n1_16;
    private javax.swing.JTextField n2_16;
    private javax.swing.JTextField n3_16;
    private javax.swing.JTextField n4_16;
    private javax.swing.JTextField n5_16;
    private javax.swing.JTextField n6_16;
    private javax.swing.JTextField n7_16;
    private javax.swing.JTextField n8_16;
    private javax.swing.JTextField octavo_a1;
    private javax.swing.JTextField octavo_b1;
    private javax.swing.JTextField octavo_e1;
    private javax.swing.JTextField octavo_f1;
    private javax.swing.JTextField r_8a_17;
    private javax.swing.JTextField r_8b_17;
    private javax.swing.JTextField r_8e_17;
    private javax.swing.JTextField r_8f_17;
    private javax.swing.JTextField r_semia_t18;
    private javax.swing.JTextField r_semia_t19;
    private javax.swing.JTextField r_tyc_1_t17;
    private javax.swing.JTextField r_tyc_2_t17;
    private javax.swing.JTextField re10_t17;
    private javax.swing.JTextField re11_t17;
    private javax.swing.JTextField re12_t17;
    private javax.swing.JTextField re1_t17;
    private javax.swing.JTextField re2_t17;
    private javax.swing.JTextField re3_t17;
    private javax.swing.JTextField re4_t17;
    private javax.swing.JTextField re9_t17;
    private javax.swing.JButton salir_n16;
    private javax.swing.JTextField semi_a_t17;
    private javax.swing.JTextField semi_c_t17;
    private javax.swing.JLabel tercerpuesto17;
    private javax.swing.JLabel torneo_lbl3;
    private javax.swing.JTextField tyc_1_t17;
    private javax.swing.JTextField tyc_2_t17;
    private javax.swing.JLabel tyc_lbl_t18;
    private javax.swing.JButton volver_n16;
    // End of variables declaration//GEN-END:variables
}
